port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
unified-delay: true
tcp-concurrent: true
external-controller: :9090

dns:
  enabled: true
  listen: ':53'
  ipv6: true
  enhanced-mode: fake-ip                    # 添加 fake-ip 模式
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:                          # 过滤本地域名
    - '+.lan'
    - '+.local'
    - 'localhost.ptlogin2.qq.com'
  nameserver:
    - 119.29.29.29                         # 国内 IPv4
    - 223.5.5.5
    - 2402:4e00::                          # 国内 IPv6（腾讯）
    - 2400:3200::1                         # 国内 IPv6（阿里）
  fallback:
    - https://8.8.8.8/dns-query            # 使用 DoH 避免污染
    - https://1.1.1.1/dns-query
    - https://[2001:4860:4860::8888]/dns-query
  fallback-filter:                         # 添加智能分流
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.googleapis.com'
      - '+.github.com'
      - '+.youtube.com'

bind-address: "*"
ipv6: true
cfw-bypass:
  - qq.com
  - music.163.com
  - '*.music.126.net'
  - localhost
  - 127.*
  - 10.*
  - 172.16.*/12                            
  - 192.168.*
  - <local>

cfw-latency-timeout: 3000                 
