port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
unified-delay: true
tcp-concurrent: true
external-controller: :9090
dns:
  enabled: true
  listen: ':53'
  ipv6: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - udp://[2001:4860:4860::8888]:53
    - udp://[2001:4860:4860::8844]:53
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
bind-address: "*"
ipv6: true
cfw-bypass:
  - qq.com
  - music.163.com
  - '*.music.126.net'
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
